services:
  theownitguy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: theownitguy-website
    networks:
      - ownitguy-tunnel
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    networks:
      - ownitguy-tunnel
    restart: unless-stopped
    depends_on:
      - theownitguy

networks:
  ownitguy-tunnel:
    driver: bridge
